//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Sperm.rc
//
#define EDGEIMAGE                       0
#define PADDEDIMAGE                     1
#define ORIGINIMAGE                     2
#define IDCANCEL2                       3
#define NUMPERPAGE                      50
#define IDD_ABOUTBOX                    100
#define IDB_SPLASH                      102
#define CG_IDR_POPUP_SPERM_VIEW         104
#define IDD_LIVEDETECTED_PAMA_SETTING   104
#define ID_PROGRESS                     105
#define IDD_DIALOG_MORPHAPARAMETER      106
#define ID_MY_STATUSBAR                 107
#define USER_SHOW_SPERM                 109
#define USER_SETCOL_WIDTH               110
#define USER_MESSAGE_AFTERWRITEDATA     111
#define USER_MESSAGE_TARGETMARKANDCENTERMARK 113
#define USER_MSG_AFTERSEQUENCEANALYSE   114
#define USER_MSG_SHOW_COMPARE_PRINT_BTN 116
#define USER_MESSAGE_CLICKLIST_MSG      117
#define USER_MSG_SHOW_DEL_SEL_BTN       118
#define USER_MSG_SHOW_MOPHY_DEL_SEL_BTN 119
#define USER_MSG_SHOW_PRINT_BTN         120
#define MOVE_SHOW_TIMER                 121
#define MSG_GET_CRYSTAL_IAPP_PTR        122
#define IDR_MAINFRAME                   128
#define IDR_SPERMTYPE                   129
#define CG_IDR_POPUP_USERCHANGE         129
#define IDD_PTNDLG                      130
#define IDD_DIALOG_VIEW2                131
#define IDD_DIALOG_RESULT               131
#define IDD_DIALOG_VIEW3                132
#define IDD_DIALOG_BUTTON               132
#define IDD_DIALOG_DISPLAY              139
#define IDD_DIALOG_BROWSER              140
#define IDB_BITMAP1                     147
#define IDD_DIALOG1                     148
#define IDD_SYSTEM_LOGIN                148
#define IDD_MORPHOLOGY                  149
#define IDD_MORPHOLOGY_SAMPLE           150
#define IDD_PATIENT                     152
#define IDD_OPTION                      153
#define IDD_DATASOURCE_OPTION           153
#define IDD_DIALOG_SETTING              154
#define IDD_ADJUST                      156
#define IDD_DIALOG_TRACK                157
#define IDD_PRO_CTRL                    158
#define IDD_SPERM_INFO                  160
#define IDD_DIALOG2                     161
#define IDD_DIALOG_LIVEDETECT           162
#define IDD_DIALOG_MORPHADETECT         163
#define IDD_DIALOG_ORIGINIMAGE          164
#define IDD_DIALOG_RESULTIMAGE          165
#define IDD_DIALOG3                     166
#define IDD_DIALOG_MORPHASET            166
#define IDI_ICON_RIGHTARROW             169
#define IDI_ICON_LEFTARROW              170
#define IDD_DIALOG_RETRIVE              171
#define IDD_DIALOG_MORPHA_RETRIVE       172
#define IDD_DIALOG_LIVE_RETRIVE         173
#define IDD_DIALOG_REGESTER             174
#define IDD_DIALOG_LIVENESSRESULT       175
#define IDD_DIALOG_LIVEIMAGE            176
#define IDD_DIALOG_USERMANAGE           178
#define IDD_DIALOG_MORPHAIMGPAD         179
#define IDD_DIALOG_MORPHAIMGEDGE        180
#define IDD_DIALOG_MORPHARESULT         181
#define IDD_DLG_COMBINATION_ANALYSE     182
#define IDD_ACTIVE_RESULT_PROPPAGE      187
#define IDD_MOPHY_RESULT_PROPPAGE       188
#define IDD_FLUORE_RESULT_PROPPAGE      189
#define IDD_PTNDLG1                     190
#define IDD_DIALOG_MORPHA_DATA_GATHER   190
#define IDD_CLASS_DLG                   191
#define IDD_PATIENT_INFO_QUERY          191
#define IDD_SYSTEM_REGISTER             192
#define IDC_BUTTON1                     1000
#define IDC_BTN_FIRSTPAGE               1000
#define IDC_BTN_PLAY                    1000
#define IDC_BTN_ADD_DOCTOR              1000
#define IDC_BTN_COMPUT                  1000
#define IDC_BTN_SEL_OK                  1000
#define IDC_BUTTON2                     1001
#define IDC_BUTTON_USERDELETE           1001
#define IDC_BTN_PREPAGE                 1001
#define IDC_BTN_PAUSE                   1001
#define IDC_BTN_QUERY                   1001
#define IDC_BTN_RPT_PRINT               1001
#define IDC_BUTTON3                     1002
#define IDC_BTN_NEXTPAGE                1002
#define IDC_BTN_STOP                    1002
#define IDC_BUTTON4                     1003
#define IDC_SLIDER1                     1003
#define IDC_BTN_LASTPAGE                1003
#define IDC_SLIDER_GRAPH                1003
#define IDC_SLIDER_THRESH_ADJUST        1003
#define IDC_BUTTON5                     1004
#define IDC_SLIDER2                     1004
#define IDC_BTN_RESUME                  1004
#define IDC_BTN_PRINTSIMPLE             1004
#define IDC_BTN_PRINT                   1004
#define IDC_SLIDER_GROW_STEP            1004
#define IDC_BUTTON6                     1005
#define IDC_SLIDER3                     1005
#define IDC_BTN_PRINTMULTIHEAD          1005
#define IDC_BTN_INFO_MODIFY             1005
#define IDC_BTN_USER_HANDLE             1005
#define IDC_SLIDER_THRESH_ADJUST_PART   1005
#define IDC_BUTTON7                     1006
#define IDC_SLIDER4                     1006
#define IDC_INF_LENGHT                  1006
#define IDC_BTN_COMPARE_PRINT           1006
#define IDC_BTN_LESS                    1006
#define IDC_BTN_MOVE_SHOW               1006
#define IDC_BTN_LIVEDETECTED            1007
#define IDC_EDIT1                       1007
#define IDC_INF_WIDTH                   1007
#define IDC_BTN_INFO_MODIFY_MOPY        1007
#define IDC_BTN_BIGGER                  1007
#define IDC_EDIT_STR_DIAGNOSTIC         1007
#define IDC_BTN_EXIT                    1008
#define IDC_EDIT2                       1008
#define IDC_INF_AREA                    1008
#define IDC_BTN_PATIENT_INFO_QUERY      1008
#define IDC_EDIT_RPT_DOC                1008
#define IDC_BUTTON10                    1009
#define IDC_EDIT3                       1009
#define IDC_INF_PERIMETER               1009
#define IDC_BUTTON11                    1010
#define IDC_EDIT4                       1010
#define IDC_INF_ELLIPTICITY             1010
#define IDC_BUTTON12                    1011
#define IDC_EDIT5                       1011
#define IDC_INF_PERFOR_AREA             1011
#define IDC_EDIT6                       1012
#define IDC_INF_HEAD_AREA               1012
#define IDC_EDIT7                       1013
#define IDC_INF_HEAD_PERFOR_AREA        1013
#define IDC_EDIT8                       1014
#define IDC_INF_MITOSOMA_LENGHT         1014
#define IDC_EDIT9                       1015
#define IDC_INF_MITOSOMA_WIDTH          1015
#define IDC_EDIT10                      1016
#define IDC_INF_MITOSOMA_DEVANGLE       1016
#define IDC_EDIT11                      1017
#define IDC_INF_RUGA                    1017
#define IDC_RADIO1                      1018
#define IDC_INF_EXTENSION               1018
#define IDC_EDIT_C_CLASS                1018
#define IDC_RADIO2                      1019
#define IDC_INF_SYMMETRY                1019
#define IDC_EDIT_D_CLASS                1019
#define IDC_RADIO3                      1020
#define IDC_SUP_LENGHT                  1020
#define IDC_RADIO4                      1021
#define IDC_SUP_WIDTH                   1021
#define IDC_RADIO5                      1022
#define IDC_SUP_AREA                    1022
#define IDC_BUTTON13                    1023
#define IDC_RADIO6                      1023
#define IDC_SUP_PERIMETER               1023
#define IDC_RADIO12                     1024
#define IDC_SUP_ELLIPTICITY             1024
#define IDC_SUP_PERFOR_AREA             1025
#define IDC_RADIO7                      1026
#define IDC_SUP_EXTENSION               1026
#define IDC_RADIO8                      1027
#define IDC_SUP_HEAD_AREA               1027
#define IDC_RADIO9                      1028
#define IDC_SUP_HEAD_PERFOR_AREA        1028
#define IDC_RADIO10                     1029
#define IDC_SUP_MITOSOMA_LENGHT         1029
#define IDC_RADIO11                     1030
#define IDC_SUP_MITOSOMA_WIDTH          1030
#define IDC_RADIO13                     1031
#define IDC_SUP_MITOSOMA_DEVANGLE       1031
#define IDC_RADIO14                     1032
#define IDC_SUP_RUGA                    1032
#define IDC_RADIO15                     1033
#define IDC_SUP_SYMMETRY                1033
#define IDC_RADIO16                     1034
#define IDC_RADIO17                     1037
#define IDC_RADIO18                     1038
#define IDC_BTN_LOAD                    1039
#define IDC_RADIO19                     1039
#define IDC_CLASSIFY                    1041
#define IDC_LIST2                       1042
#define IDS_SAMPLE                      1043
#define IDC_DINGTI                      1046
#define IDC_TUOYUAN                     1047
#define IDC_TAIL_LENTH                  1048
#define IDC_HEAD_LENTH                  1049
#define IDC_HEAD_WIDTH                  1050
#define IDC_PERIMETER                   1051
#define IDC_AREA                        1052
#define IDC_IMAGE_RECT                  1053
#define USER_MM_CAP_FRM_HAS_BEEN_FINISHED 1055
#define IDC_SAMPLENUM                   1058
#define IDC_NORMALRATIO                 1059
#define IDC_AREAMEAN                    1060
#define IDC_LENTHMEAN                   1061
#define IDC_WIDTHMEAN                   1062
#define IDC_ABNORMALRATIO               1063
#define IDC_PERIMERMEAN                 1063
#define IDC_ABAREAMEAN                  1064
#define IDC_ABLENTHMEAN                 1065
#define IDC_WEIBULENTHMEAN              1065
#define IDC_ABWIDTHMEAN                 1066
#define IDC_CLASSIFY_GRAPHY             1067
#define IDC_MOR_CALCULATE               1068
#define IDC_ANN_TRAIN                   1069
#define IDC_AUTO_STATIC                 1070
#define IDC_DATA_INIT                   1071
#define IDC_CHARACT_EXT                 1072
#define IDC_COMBO2                      1075
#define IDC_COMBO_LIQUIFYTIME           1075
#define IDC_COMBOX                      1083
#define IDC_LIST5                       1087
#define IDC_EDIT12                      1088
#define IDC_EDIT13                      1089
#define IDC_EDIT14                      1090
#define IDC_EDIT_DILUTIONRATIO          1090
#define IDC_EDIT15                      1091
#define IDC_EDIT_SPERMVOLUME            1091
#define IDC_EDIT16                      1092
#define IDC_EDIT_COHENSION              1092
#define IDC_EDIT17                      1093
#define IDC_EDIT_THICKNESS              1093
#define IDC_EDIT18                      1094
#define IDC_EDIT_LIQUIFYSTATE           1094
#define IDC_COMBO4                      1095
#define IDC_COMBO_SPERMWAY              1095
#define IDC_COMBO5                      1096
#define IDC_COMBO_THICKNESS             1096
#define IDC_EDIT_AGE                    1096
#define IDC_COMBO6                      1097
#define IDC_COMBO_COHENSION             1097
#define IDC_EDIT_SHAPE                  1097
#define IDC_COMBO7                      1098
#define IDC_COMBO_SMELL                 1098
#define IDC_EDIT_ROOMTEMPERA            1098
#define IDC_COMBO8                      1099
#define IDC_COMBO_SHAPE                 1099
#define IDC_EDIT_PH                     1099
#define IDC_COMBO9                      1100
#define IDC_COMBO_PH                    1100
#define IDC_EDIT_ABSTINENCY             1100
#define IDC_PATIENT                     1101
#define IDC_SETTING                     1102
#define IDC_EDIT_SPERMWAY               1102
#define IDC_BUTTON_MORPHADETECT         1103
#define IDC_EDIT_LIQUIFYTIME            1103
#define IDC_CAIJI_IMAGE                 1105
#define IDC_FENGE_IMAGE                 1106
#define IDC_CHULI_IMAGE                 1107
#define IDC_ZHONG                       1109
#define IDC_CURRENT_CAL                 1110
#define IDC_DEFAULT_CAL                 1111
#define IDC_EROTION                     1112
#define IDC_LIST3                       1114
#define IDC_LIST4                       1115
#define IDC_TRACK_IMAGE                 1116
#define IDC_PROGRESS1                   1117
#define IDC_PROGRESS2                   1118
#define IDC_NUM                         1119
#define IDC_PROCESS                     1120
#define IDC_TRACK_NUM                   1122
#define USER_MESSAGE_SHOWLIVEPROGRESS   1124
#define USER_MESSAGE_SHOW_CAPTURE_PROGRESS 1126
#define IDC_LIST6                       1128
#define IDC_CLOSE                       1130
#define IDC_TRACK_INFO                  1131
#define IDC_OUTPUT                      1132
#define IDC_INPUT_DATA_BASE             1133
#define IDC_SERVER_NAME                 1134
#define IDC_DATETIMEPICKER_SPERMGETDATE 1135
#define IDC_DATETIMEPICKER_SPERMGETTIME 1136
#define IDC_DATETIMEPICKER_DETECTDATE   1137
#define IDC_DATETIMEPICKER_DETECTTIME   1138
#define IDC_EDIT_SPERMCOLOR             1139
#define IDC_EDIT_MEMORY                 1140
#define IDC_EDIT_SMELL                  1140
#define IDC_BTN_AUTOANALYSE             1142
#define IDC_BTN_FINISHDETECT            1143
#define IDC_STATIC_DETECTNUM            1144
#define IDC_BTN_CONTINUEDETECT          1145
#define IDC_SPIN_SPERMSZ_HIGH           1146
#define IDC_SPIN_SPERMSZ_LOW            1147
#define IDC_EDIT_SPERMSZ_LOW            1148
#define IDC_EDIT_SPERMSZ_HIGH           1149
#define IDC_SPIN_GRAYVALUE              1150
#define IDC_EDIT_GRAYVALUE              1151
#define IDC_SLIDER_GRAYVALUE            1152
#define IDC_BTN_PAM_SETTING             1153
#define IDC_BTN_MODE_CHANGE             1154
#define IDC_STATIC_LENGTH               1155
#define IDC_BTN_MOVESHOW                1155
#define IDC_STATIC_WIDTH                1156
#define IDC_EDIT_ROUNDNESS              1156
#define IDC_STATIC_PERIMETER            1157
#define IDC_SPIN_GRAYVALUE2             1157
#define IDC_STATIC_AREA                 1158
#define IDC_STATIC_ELLIPTICITY          1159
#define IDC_STATIC_PERFOR_AREA          1160
#define IDC_STATIC_EXTENSION            1161
#define IDC_STATIC_HEAD_AREA            1162
#define IDC_STATIC_HEAD_PERFOR_AREA     1163
#define IDC_STATIC_MITOSOMA_LENGHT      1164
#define IDC_STATIC_MITOSOMA_WIDTH       1165
#define IDC_STATIC_MITOSOMA_DEVANGLE    1166
#define IDC_STATIC_RUGA                 1167
#define IDC_STATIC_SYMMETRY             1168
#define IDC_BUTTON_MORPHADETECT_CONTINUE 1169
#define IDC_BUTTON_MORPHADETECT_FINISH  1170
#define IDC_STATIC_STRINFO              1171
#define IDC_STATIC_ISNORMAL             1172
#define IDC_SPERM_BMP_RECT              1173
#define IDC_BUTTON_MORPHADETECT_RESTORE 1173
#define IDC_STATIC_SHOWIMAGE            1174
#define IDC_BUTTON_MORPHADETECT_PARAMETER 1175
#define IDC_CHECK_RECTANGLE             1177
#define IDC_COMBO_SHOWOPT               1178
#define IDC_ABNPOS_HEAD                 1179
#define IDC_ABNPOS_PERFOR               1180
#define IDC_RADIO_SMALLPOINT            1180
#define IDC_ABNPOS_TAIL                 1181
#define IDC_RADIO21                     1181
#define IDC_RADIO23                     1183
#define IDC_RADIO_HEAD                  1184
#define IDC_RADIO_PERFOR                1185
#define IDC_RADIO_TAIL                  1186
#define IDC_COMBO_SPERMVOLUME           1187
#define IDC_COMBO_ABSTINENCY            1188
#define IDC_COMBO_ROOMTEMPERA           1189
#define IDC_EDIT_DETECTNO               1190
#define IDC_EDIT_NAME                   1191
#define IDC_EDIT_CASENO                 1193
#define IDC_EDIT_DETECTDOCTOR           1194
#define IDC_EDIT_SENDDOCTOR             1195
#define IDC_COMBO_AGE                   1196
#define IDC_EDIT_PATIENTNAME            1197
#define IDC_EDIT_SAMPLENO               1198
#define IDC_SUM_NUM                     1198
#define IDC_BUTTON_DELETESPERM          1199
#define IDC_LD_PROGRESS_INFO            1199
#define IDC_DETECT_INFO                 1200
#define IDC_CHK_NAME                    1201
#define IDC_CHK_DETECTNO                1202
#define IDC_CHK_CASENO                  1202
#define IDC_CHK_DETECTDATE              1203
#define IDC_DATETIMEPICKER_INPUT_FROM   1206
#define IDC_DATETIMEPICKER_INPUT_TO     1207
#define IDC_CHK_OTHER                   1208
#define IDC_COMBO_OTHERSELECTION        1209
#define IDC_DATAGRID_MORPHA             1212
#define IDC_EDIT_INPUTDETECTNO          1214
#define IDC_EDIT_INPUTNAME              1215
#define IDC_EDIT_OTHERVALUE             1216
#define IDC_EDIT_INPUTCASENO            1216
#define IDMYOK                          1218
#define IDC_EDIT_USERNAME               1219
#define IDC_BUTTON_REGSTER              1220
#define IDC_EDIT_PASS1                  1220
#define IDC_DEPTH                       1220
#define IDC_BUTTON_INQUERY              1221
#define IDC_COMBO_SERVER_NAME           1221
#define IDC_EDIT_PASS2                  1221
#define IDC_ENLARGE_RATIO               1221
#define IDC_STATIC_QUERY                1222
#define IDC_BUTTON_QUERY                1222
#define IDC_STR_THRD                    1222
#define IDC_LIN_THRD                    1223
#define IDC_EDIT_PASS                   1224
#define IDC_CUR_THRD                    1224
#define IDC_V0_THRD                     1225
#define IDC_STATIC_QUERYINFO            1225
#define IDC_V1_THRD                     1226
#define IDC_V2_THRD                     1227
#define IDC_DATAGRID                    1227
#define IDC_CAPTURE_NUM                 1228
#define IDC_LIST_DATA                   1229
#define IDC_LIST_MORPHADATA             1232
#define IDC_STATIC_IMAGE                1233
#define IDC_LIST_USER                   1234
#define IDC_BUTTON_USERADD              1235
#define IDC_BUTTON_MORPHAINQUERY        1236
#define IDC_ANALYSEPROGRESS             1237
#define IDC_LISTDATA                    1238
#define IDC_RESPOS                      1239
#define IDC_EDGE_IMAGE                  1241
#define IDC_PAD_IMAGE                   1242
#define IDC_PAGENUM                     1243
#define IDC_CMB_DEVICE                  1244
#define IDC_STATIC_TEST                 1245
#define IDC_MICROSCOPE                  1246
#define ID_BTN_PRINT                    1247
#define IDC_COMBO_LIQUIFYSTATE          1249
#define IDC_COMBO_DETECTDOCTOR          1250
#define IDC_COMBO_SENDDOCTOR            1251
#define IDC_EDIT_INPUTPATIENTNO         1252
#define IDC_BTN_COMBIN_ANALYSE          1253
#define IDC_SHEET_POS_STATIC            1255
#define IDC_LIST_ACTIVE_RESULT          1256
#define IDC_INPUT_DATETIMEPICKER        1257
#define IDC_LIST_MOPHY_RESULT           1259
#define IDC_LIST_FLUORE_RESULT          1260
#define IDC_CHECK_ACTIVE                1262
#define IDC_CHECK_MOPHY                 1263
#define IDC_CHECK_FLUORE                1264
#define IDC_SPIN1                       1265
#define IDC_CHECK_DATETIME              1266
#define IDC_ACTIVEXREPORTVIEWER2        1268
#define IDC_ACTIVEXREPORTVIEWERyyy      1269
#define IDC_REPOSITORYEXPLORER1         1270
#define IDC_STATIC_INFO                 1271
#define IDC_EDIT_V                      1274
#define IDC_BTN_ROUND_LESS              1275
#define IDC_BTN_ROUND_BIGGER            1276
#define IDC_RADIO_A                     1276
#define IDC_RADIO_B                     1277
#define IDC_RADIO_C                     1278
#define IDC_RADIO_D                     1279
#define IDC_BTN_DEL_SEL                 1281
#define IDC_STATIC_1                    1282
#define IDC_STATIC_2                    1283
#define IDC_STATIC_3                    1284
#define IDC_STATIC_4                    1285
#define IDC_STATIC_5                    1286
#define IDC_STATIC_ZHISHU               1287
#define IDC_EDIT_MIDU                   1288
#define IDC_EDIT_HUOLV                  1289
#define IDC_EDIT_XINGTAILV              1291
#define IDC_EDIT_WANZHENGLV             1292
#define IDC_EDIT_FANYINLV               1293
#define IDC_EDIT_SUDU                   1294
#define IDC_EDIT_TOT_SPERM_NUM          1294
#define IDC_EDIT_MOVE_SPERM_NUM         1295
#define IDC_EDIT_SPERM_DENSITY          1296
#define IDC_EDIT_LIN_NUM                1297
#define IDC_EDIT_MOVE_RATIO             1298
#define IDC_EDIT_CUR_NUM                1299
#define IDC_EDIT_ACTIVE_NUM             1300
#define IDC_EDIT_ACTIVE_DENSITY         1301
#define IDC_EDIT_A_CLASS                1302
#define IDC_EDIT_B_CLASS                1303
#define IDC_PATIENT_INFO_LIST           1304
#define IDC_STATIC_THRESH_ADJUST        1305
#define IDC_STATIC_GROW_STEP            1306
#define IDC_STATIC_THRESH_ADJUST_PART   1307
#define IDC_POOR                        1308
#define IDC_RICH                        1309
#define IDD_IMAGE_LIST                  1353
#define IDC_ACTIVEXREPORTVIEWER1        17071
#define ID_PLAY_START                   32771
#define ID_PAUSE_PLAY                   32772
#define ID_RESUME_PLAY                  32773
#define ID_FILE_STOP                    32774
#define ID_SCREEN_CAPTURE               32776
#define ID_IMAGE                        32779
#define ID_VEDIO                        32780
#define ID_TARGET_MARK                  32781
#define ID_NEXT_IMAGE                   32782
#define ID_PRE_IMAGE                    32783
#define ID_TRACER                       32784
#define ID_START                        32786
#define ID_RESTART                      32787
#define ID_OVER                         32788
#define ID_OPTION                       32789
#define ID_OPTION_FRAME                 32791
#define ID_MORPH                        32792
#define ID_CANNY                        32793
#define ID_MORPHOLOGY                   32795
#define ID_DATAINIT                     32797
#define ID_CHOOSE_SAMPLE                32798
#define ID_CHOOSE_WEIGHT                32799
#define ID_TRAIN_ANN                    32800
#define ID_CLASSIFIER                   32801
#define ID_MORPHOLOGY_ANALYSE           32802
#define ID_PRINT                        32803
#define ID_PRINT_TABLE                  32803
#define ID_PRINT_PREVIEW                32804
#define ID_PRINT_SETUP                  32805
#define ID_SET_PAT_INFO                 32806
#define ID_DATA_OPTION_S                32808
#define ID_CAMERA_OPEN                  32809
#define ID_CAMERA_SETTING               32810
#define ID_RESOLUTION_SETTING           32811
#define ID_VEDIO_SAVE                   32812
#define ID_SAVING_OVER                  32813
#define ID_PLAY_SETTINT                 32814
#define ID_ADJUST                       32815
#define ID_GRAY_TRACE                   32816
#define ID_BIN_TRACE                    32817
#define ID_DIF_IMAGE                    32818
#define ID_GRAY_BIN                     32819
#define ID_IMAGE_THIN                   32820
#define ID_ERASE                        32821
#define ID_TRACK                        32822
#define ID_TARGET_REC                   32823
#define ID_AVE_PATH                     32824
#define ID_AVE_PATH_FIX                 32825
#define ID_PARAMETERS_CAL               32827
#define ID_TRACK_INFO                   32828
#define ID_CONTROL_TAB                  32829
#define ID_RE_DIS                       32830
#define ID_BUTTON32843                  32843
#define ID_BUTTON_LEFTARROW             32844
#define ID_BUTTON_RIGHTARROW            32845
#define ID_DELETE_SPERM                 32846
#define ID_SPERM_MORSET                 32847
#define ID_DATA_RETRIVE                 32848
#define ID_DATA_BACKUP                  32849
#define ID_DATA_MORPHA                  32850
#define ID_DATA_LIVE                    32851
#define ID_DATA_RESTOR                  32852
#define ID_USER_MANAGE                  32853
#define ID_FILE_OPEN_S                  32854
#define ID_SPERM_ADD                    32855
#define ID_SPERM_DEL                    32856
#define IDC_MENU_GLOBAL_ANALYSE         32858
#define ID_NORMAL_SPERM                 32859
#define ID_MORPHA_GATHER_DATA           32860
#define ID_MENU_A                       32861
#define ID_MENU_B                       32862
#define ID_MENU_C                       32863
#define ID_MENU_D                       32864
#define ID_MENU_ADD2DB                  32865
#define ID_MENU_DB_VERDICT              32866
#define ID_MENU_ADD_NORMAL2DB           32868
#define ID_MENU_ADD_ABNORMAL2DB         32869
#define ID_REG                          32870
#define ID_32871                        32871
#define ID_DATA_OPTION_NEW              32872

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        195
#define _APS_NEXT_COMMAND_VALUE         32873
#define _APS_NEXT_CONTROL_VALUE         1309
#define _APS_NEXT_SYMED_VALUE           123
#endif
#endif
