#if !defined(AFX_CRYSTALREPORTVIEWER10_H__29F117B4_C711_4BC7_9491_2244BE9A5F87__INCLUDED_)
#define AFX_CRYSTALREPORTVIEWER10_H__29F117B4_C711_4BC7_9491_2244BE9A5F87__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCrystalReportViewer10 wrapper class

class CCrystalReportViewer10 : public CWnd
{
protected:
	DECLARE_DYNCREATE(CCrystalReportViewer10)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xa1b8a30b, 0x8aaa, 0x4a3e, { 0x88, 0x69, 0x1d, 0xa5, 0x9, 0xe8, 0xa0, 0x11 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	LPUNKNOWN GetReportSource();
	void SetReportSource(LPUNKNOWN newValue);
	BOOL GetDisplayGroupTree();
	void SetDisplayGroupTree(BOOL bNewValue);
	BOOL GetDisplayToolbar();
	void SetDisplayToolbar(BOOL bNewValue);
	BOOL GetEnableGroupTree();
	void SetEnableGroupTree(BOOL bNewValue);
	BOOL GetEnableNavigationControls();
	void SetEnableNavigationControls(BOOL bNewValue);
	BOOL GetEnableStopButton();
	void SetEnableStopButton(BOOL bNewValue);
	BOOL GetEnablePrintButton();
	void SetEnablePrintButton(BOOL bNewValue);
	BOOL GetEnableZoomControl();
	void SetEnableZoomControl(BOOL bNewValue);
	BOOL GetEnableCloseButton();
	void SetEnableCloseButton(BOOL bNewValue);
	BOOL GetEnableProgressControl();
	void SetEnableProgressControl(BOOL bNewValue);
	BOOL GetEnableSearchControl();
	void SetEnableSearchControl(BOOL bNewValue);
	BOOL GetEnableRefreshButton();
	void SetEnableRefreshButton(BOOL bNewValue);
	BOOL GetEnableDrillDown();
	void SetEnableDrillDown(BOOL bNewValue);
	BOOL GetEnableAnimationCtrl();
	void SetEnableAnimationCtrl(BOOL bNewValue);
	BOOL GetEnableSelectExpertButton();
	void SetEnableSelectExpertButton(BOOL bNewValue);
	void ViewReport();
	BOOL GetEnableToolbar();
	void SetEnableToolbar(BOOL bNewValue);
	BOOL GetDisplayBorder();
	void SetDisplayBorder(BOOL bNewValue);
	BOOL GetDisplayTabs();
	void SetDisplayTabs(BOOL bNewValue);
	BOOL GetDisplayBackgroundEdge();
	void SetDisplayBackgroundEdge(BOOL bNewValue);
	LPDISPATCH GetTrackCursorInfo();
	short GetActiveViewIndex();
	short GetViewCount();
	void ActivateView(const VARIANT& Index);
	void AddView(const VARIANT& GroupPath);
	void CloseView(const VARIANT& Index);
	VARIANT GetViewPath(short Index);
	void PrintReport();
	void Refresh();
	void SearchForText(LPCTSTR Text);
	void ShowFirstPage();
	void ShowNextPage();
	void ShowPreviousPage();
	void ShowLastPage();
	void ShowNthPage(short PageNumber);
	void Zoom(short ZoomLevel);
	long GetCurrentPageNumber();
	void ShowGroup(const VARIANT& GroupPath);
	BOOL GetIsBusy();
	BOOL GetEnablePopupMenu();
	void SetEnablePopupMenu(BOOL bNewValue);
	BOOL GetEnableExportButton();
	void SetEnableExportButton(BOOL bNewValue);
	BOOL GetEnableSearchExpertButton();
	void SetEnableSearchExpertButton(BOOL bNewValue);
	void SearchByFormula(LPCTSTR formula);
	CString GetViewName(BSTR* pTabName);
	BOOL GetEnableHelpButton();
	void SetEnableHelpButton(BOOL bNewValue);
	VARIANT GetGroup();
	void GetLastPageNumber(long* pageN, BOOL* lastPageKnown);
	void RefreshEx(BOOL refreshServerData);
	BOOL GetLaunchHTTPHyperlinksInNewBrowser();
	void SetLaunchHTTPHyperlinksInNewBrowser(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CRYSTALREPORTVIEWER10_H__29F117B4_C711_4BC7_9491_2244BE9A5F87__INCLUDED_)
